from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

#https://flask-sqlalchemy.palletsprojects.com/en/2.x/models/https://flask-sqlalchemy.palletsprojects.com/en/2.x/models/
class Ticket(db.Model):
    #Ticket DB fields
    id = db.Column(db.Integer, primary_key=True)#autogenerated
    name = db.Column(db.String(100),nullable=False)
    status = db.Column(db.Integer, nullable=False)#statuses_dict[0,1,2,3]
    url = db.Column(db.String(100),nullable=True)#optional
    statuses_dict = {
            0: 'Reported',
            1: 'In Progress',
            2: 'In Review',
            3: 'Resolved'
            }
    def status_string(self):
        return self.statuses_dict[self.status]

    def to_json(self):
        """
        Return the JSON serilizable format
        """
        return {
            'id':self.id,
            'name':self.name,
            'status':self.status_string(),
            'url':self.url
            }
